{% set name = "json-spec" %}
{% set version = "0.11.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: c767d6599dee08cd8fa9cce40daad42ef09e469c864acb29a04997de7f8e9d3b

build:
  number: 0
  noarch: python
  entry_points:
    - json = jsonspec.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - six

test:
  imports:
    - jsonspec
    - jsonspec.misc
  commands:
    - pip check
    - json --help
  requires:
    - pip

about:
  home: http://py.errorist.io/json-spec
  summary: Implements JSON Schema, JSON Pointer and JSON Reference.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - wolfv
