{% set name = "json-spec" %}
{% set version = "0.12.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 0a1fe48bf3e6bce39668b4bacb99e479429138d77b16ab25c482b3238d4702e0

build:
  number: 0
  noarch: python
  entry_points:
    - json = jsonspec.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.10,<4.0
  run:
    - python >=3.10,<4.0
    - termcolor
    - importlib-metadata >=5.0.0,<6

test:
  imports:
    - jsonspec
    - jsonspec.misc
  commands:
    - pip check
    - json --help
  requires:
    - pip

about:
  home: https://json-spec.readthedocs.org/
  doc_url: https://json-spec.readthedocs.org/
  dev_url: https://github.com/johnnoone/json-spec
  summary: Implements JSON Schema, JSON Pointer and JSON Reference.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - wolfv
